---
- name: To install apache2 in both the instances
  apt: name={{item}} state=present 
  with_items:
    - apache2
    - libapache2-mod-wsgi

- name: To start the apache2 services
  service: name=apache2 state=started enabled=yes
    
- name: Ensure mod Wsgi started
  apache2_module: name=wsgi state=present
  notify: restart apache2