---
- hosts: loadbalancer
  gather_facts: false
  become: true
  tasks:
    - name: Draining the loadbalancer
      service: name=nginx state=stopped
    - wait_for: port=80 state=drained
- hosts: webserver
  become: true
  tasks:
    - name: Restarting web servers
      service: name=apache2 state=stopped
    - wait_for: port=80 state=stopped
- hosts: database
  become: true
  tasks:
    - name: Restarting Db engine
      service: name=mysql state=restarted
    - wait_for: port=80
- hosts: webserver
  become: true
  tasks:
    - name: bringing web server up
      service: name=apache2 state=started
    - wait_for: port=80
- hosts: loadbalancer
  become: true
  tasks:
    - name: Allowing load and traffic
      service: name=nginx state=started
    - wait_for: port=80

